// The Phosphor icons the app uses (plan key 2k), in one place so the set stays small and consistent.
export {
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowUUpLeft,
  ArrowLeft,
  ArrowRight,
  Bridge,
  Car,
  Cube,
  CastleTurret,
  Check,
  DownloadSimple,
  FlipHorizontal,
  Flower,
  FlowerTulip,
  GridFour,
  Hand,
  HandGrabbing,
  HandTap,
  House,
  Jeep,
  Lock,
  Minus,
  Palette,
  Pause,
  PawPrint,
  Play,
  PlayCircle,
  Plus,
  Rocket,
  Sparkle,
  SpeakerHigh,
  Trash,
  UploadSimple,
  X,
} from "@phosphor-icons/react";
