// The Phosphor icons the app uses (plan key 2k), in one place so the set stays small and consistent.
export {
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  Bridge,
  Car,
  CastleTurret,
  Check,
  DownloadSimple,
  Flower,
  GridFour,
  Hand,
  House,
  Lock,
  Minus,
  PawPrint,
  Play,
  Plus,
  Rocket,
  Sparkle,
  SpeakerHigh,
  UploadSimple,
  X,
} from "@phosphor-icons/react";
