/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 snail.glb --types --keepnames --output snail.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph, type ThreeElements } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    glint120: THREE.Mesh
    glint130: THREE.Mesh
    Sphere003: THREE.Mesh
    glint020: THREE.Mesh
    glint030: THREE.Mesh
    Sphere: THREE.Mesh
    mouth: THREE.Mesh
    shell0pane: THREE.Mesh
    shell0rim: THREE.Mesh
    shell1pane: THREE.Mesh
    shell1rim: THREE.Mesh
    shell2pane: THREE.Mesh
    shell2rim: THREE.Mesh
    shell3pane: THREE.Mesh
    shell3rim: THREE.Mesh
    body: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshPhysicalMaterial
    PaletteMaterial007: THREE.MeshPhysicalMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
}

export function Model(props: ThreeElements['group'] & { onNodes?: (n: GLTFResult['nodes']) => void }) {
  const { scene } = useGLTF('/tile-builder/mock-pip/snail.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) as unknown as GLTFResult
  const { onNodes, ...rest } = props
  React.useEffect(() => onNodes?.(nodes), [nodes, onNodes])
  return (
    <group {...rest} dispose={null}>
      <primitive object={nodes.root} />
      <skinnedMesh name="body" geometry={nodes.body.geometry} material={nodes.body.material} skeleton={nodes.body.skeleton} />
    </group>
  )
}

useGLTF.preload('/tile-builder/mock-pip/snail.glb')
