/* Every word the app shows or says (the plan's rule 15). Kid words follow PRODUCT.md's voice: plain statements, sentence
   case, short; an exclamation mark only for "You can build it!" and the end of a build. */
export const APP_NAME = "Tile Steps";

export const S = {
  screens: {
    library: "Library",
    build: "Build",
    done: "Well done",
    grownups: "Grown-ups",
    tiles: "Tiles",
    settings: "Settings",
    design: "The design page",
  },
  pwa: {
    offlineReady: "Ready to use without Wi-Fi.",
  },
  kid: {
    looks: "Change how it looks",
    back: "Back to the shelf",
    hearAgain: "Hear again",
    next: "Next",
    stepBack: "Back",
    door: "This door is for grown-ups.",
    doorLabel: "Grown-ups",
    turnLeft: "Turn left",
    turnRight: "Turn right",
    mySide: "Back to my side",
    all: "All",
    more: "More",
    ages: { t: "0 to 3", a: "3 to 5", b: "6 to 8", c: "9 to 10", d: "11 to 16" },
    agesShort: { t: "0–3", a: "3–5", b: "6–8", c: "9–10", d: "11–16" },
    pickAge: "How old is the builder?",
    can: "You can build it!",
    swap: "You can build it with a swap",
    need: (n: number) => `Need ${n} more`,
    needSay: (what: string) => `You need ${what} for this one.`,
    stars: (n: number) => `${n} ${n === 1 ? "star" : "stars"}`,
    step: (i: number, n: number) => `Step ${i} of ${n}`,
    emptyTiles: "A grown-up can add your tiles behind the door.",
    emptyShelf: "No projects here yet. Try another picture.",
    cantLoad: "This one isn't on the iPad yet. Ask a grown-up to join Wi-Fi, then try again.",
    tryAgain: "Try again",
    skip: "Tap to go on",
    themes: "Themes",
    turnGroup: "Turn the model",
  },
  build: {
    fellButton: "It fell down",
    fell: "Towers fall sometimes. Builders fix them.",
    fellGrownup: "Ask a grown-up to hold it while you add the next tile.",
    backOne: "Go back one step",
    layerAgain: "Start this layer again",
    needTitle: (n: number) => `You need ${n} more ${n === 1 ? "tile" : "tiles"} for this one.`,
    startAnyway: "Start anyway",
    pickAnother: "Pick another",
    keepBuilding: "Keep building",
    model: (title: string) => `${title}, in 3D`,
    bestWithOneBrand: "This one works best with tiles of one brand.",
    forBaby: "For a grown-up to build, for a baby to look at. Magnet tiles are made for ages 3 and up: stay close, and put away any cracked tile.",
    stepTiles: "This step's tiles",
    getTiles: "Get your tiles",
    start: "Start",
    backToBuilding: "Back to building",
    tilesButton: "Tiles you need",
    total: (n: number) => `${n} ${n === 1 ? "tile" : "tiles"} in all.`,
    allSteps: "All steps",
    buildThis: "Build this step",
    closeSteps: "Close all steps",
    chooseStep: "Choose a step",
    stepNumber: (n: number) => `Step ${n}`,
  },
  oops: "That didn't work. Let's go back.",
  done: {
    party: "Well done",
    putDown: "Put the iPad down and play with what you made.",
    back: "Back to the shelf",
  },
  library: {
    ready: "You can build these",
    more: "These need a few more tiles",
    forAge: (ages: string) => `For ${ages}`,
    trucks: "Monster trucks",
    flowers: "Wildflowers",
    keepBuilding: "Keep building",
    tryThis: "Try this one",
    keepGoing: "Keep going",
    start: "Start",
  },
  firstRun: {
    homeTitle: "Add this to your Home Screen first, so it keeps your tiles",
    share: "Tap Share at the top of Safari.",
    add: "Tap Add to Home Screen, then open Tile Steps from there.",
    buildTitle: "Stand the iPad up beside the tiles and build together.",
    buildBody: "Pick a project together and follow the steps on the screen; the building happens on the table. Tap the speaker to hear a step.",
    pickLook: "Pick a style. You can change it any time with the paint palette on the shelf.",
    ok: "Got it",
  },
  /** Pip's tips (3.9), told once a build at the first step that needs one */
  tips: {
    crash: "This wall is built to fall. Crash into it!",
    brace: "This square locks the ramp, so it can't fold.",
    ramp: "A ramp leans on its tower. Push it in until it clicks.",
    roof: "Hold the walls steady while the roof goes on.",
    bigStand: "Big squares are heavy. Hold it until the next tile clicks on.",
    layer3: "Going up! Finish each layer all the way round first.",
  },
} as const;
